#!/usr/bin/python

import rospy
from metaldetector_ros.MetalDetector import MetaldetectorNode

rospy.init_node("metaldetectornode")

md = MetaldetectorNode()

while not rospy.is_shutdown():
  rospy.spin()
